logger:
  level: "INFO"
storage:
  memory:
    cleanup_interval: 2m
  db:
    host: "redis:6379"
    password: ""
server:
  grpc:
    port: ":50051"
constraints:
  login: "10/m"
  password: "100/m"
  ip: "1000/m"
