name: Rate limiter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters check
        run: make lint

      - name: Build server binary
        run: make build

      - name: Unit tests
        run: make test

  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Integration tests
        run: make integration-tests
