name: Rate limiter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters check
        run: make lint

      - name: Build server binary
        run: make build

      - name: Unit tests
        run: make test

  integration_tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and run server
        run: make run

      - name: Integration tests
        run: go test -v -race ./tests
